### ISSUE TITLE
POST request to admin/topics got Invadid request error

### ISSUE THREAD

**Issue by bttong** [ibm-messaging/event-streams-docs#2]
Hello,
I'm new to IBM message hub.  I'm testing a create topic REST API call but got the invalid request error for my POST test.  I have X-Auth-Token and Content-Type=application/json in the headers and below is the body:
{
           name: "test",
           partitions: 1,
            configs: {
                    retentionMs: 8640000
                  }
        }
Please advice on what I'm missing.
Thanks much.
Britney

**Comment by prestona** [comment]
Hi @bttong - I had a quick play around and I think there might be a couple of issues that you are hitting.  Firstly the property names need to be in double quotes (see: http://stackoverflow.com/questions/380855/json-syntax-for-property-names).  Also the retention period needs to be in a whole number of hours, and I think you dropped a zero (easily done) as 8640000 is 2.4 hours.

Here's a version that I think should work (assuming you want 24 hours of message retention):
```
{
  "name": "test",
  "partitions": 1,
  "configs": {
    "retentionMs": 86400000
  }
}
```

And here's the curl command line that I used to try this out:
```
curl -v -X POST -H 'Content-Type: application/json' -H 'Accept: */*' -H 'X-Auth-Token: <redacted>' https://<your-endpoint-here>/admin/topics -d '{"name": "test","partitions": 1,"configs": {"retentionMs": 86400000}}'
```

**Comment by bttong** [comment]
Oh doh..It works now.  Thank you so much.
